const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

export function renderAdminPage({ session, csrf, configReady, canEdit = false, canRecruit = false }) {
  let content;
  if (!session) {
    content = `<section class="admin-card"><h1>Admin sign in</h1>${configReady ? '' : '<p>Admin access is not configured. Set an administrator username and scrypt password hash in the server environment.</p>'}<form class="site-form" action="/api/admin/login" method="post" data-admin-form><input type="hidden" name="csrf" value="${esc(csrf)}"><label>Username<input name="username" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><button class="button button-dark" type="submit"${configReady ? '' : ' disabled'}>Sign in</button></form></section>`;
  } else {
    const editor = canEdit ? `<form class="site-form" action="/api/admin/content" method="post" data-admin-form data-content-editor><input type="hidden" name="csrf" value="${esc(csrf)}"><input type="hidden" name="id"><h2>Create or edit content</h2><label>Type<select name="type"><option value="actuality">Actuality</option><option value="job"${canRecruit ? '' : ' disabled'}>Job</option><option value="project">Project</option><option value="insight">Insight</option></select></label><label>Language<select name="lang"><option value="fr">Français</option><option value="en">English</option></select></label><label>Title<input name="title" maxlength="180" required></label><label>URL slug<input name="slug" maxlength="100"></label><label>Category / department<input name="category" maxlength="100"></label><label>Author (optional)<input name="author" maxlength="150"></label><label>Related service (optional)<input name="relatedService" maxlength="100"></label><label>Country (projects only)<input name="country" maxlength="100"></label><label>Client (projects only; requires permission)<input name="client" maxlength="180"></label><label class="checkbox-label"><input type="checkbox" name="clientAuthorized" value="yes"><span>Client authorization verified</span></label><label>Project type<input name="projectType" maxlength="120"></label><label>Technical scope<textarea name="scope" maxlength="5000"></textarea></label><label>Services provided<textarea name="servicesProvided" maxlength="2000"></textarea></label><label>Project year<input name="projectYear" inputmode="numeric" maxlength="4"></label><label>Verified outcome<textarea name="outcome" maxlength="3000"></textarea></label><label class="checkbox-label"><input type="checkbox" name="outcomeVerified" value="yes"><span>Outcome verified for publication</span></label><label>Job location<input name="location" maxlength="150"></label><label>Contract type<input name="contractType" maxlength="100"></label><label>Closing date<input name="closingDate" type="date"></label><label>Reference number<input name="reference" maxlength="80"></label><label>Summary<textarea name="summary" maxlength="1000" required></textarea></label><label>Body<textarea name="body" rows="8" maxlength="20000" required></textarea></label><label>Status<select name="status"><option value="draft">Draft</option><option value="review">In review</option><option value="approved">Approved</option><option value="published">Published</option><option value="archived">Archived</option></select></label><button class="button button-dark" type="submit">Save content</button></form>` : '';
    content = `<section class="admin-card"><p class="section-kicker">Role: ${esc(session.role)}</p><h1>Content and operations</h1><p>Content statuses: draft, in review, approved, published and archived. Publishing requires an approver role. Save French and English as separate records after human language review.</p>${editor}<form class="logout-form" action="/api/admin/logout" method="post" data-admin-form><input type="hidden" name="csrf" value="${esc(csrf)}"><button class="button button-outline" type="submit">Sign out</button></form><div class="admin-data" data-dashboard-data aria-live="polite"></div></section>`;
  }
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#102b55"><title>Admin | Africa Power Advisory Holdings</title><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"><script src="/admin.js" defer></script></head><body class="admin-body"><main class="admin-main"><a class="brand" href="/fr/"><img src="/assets/brand/apah-logo.svg" width="190" height="56" alt="Africa Power Advisory Holdings"></a>${content}<p class="admin-status" data-admin-message role="status" tabindex="-1"></p></main></body></html>`;
}
